apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tnoc.fullname" . }}
  labels:
    {{- include "tnoc.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
