{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tnoc.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tnoc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {{ toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - { protocol: TCP, port: {{ .Values.service.targetPort }} }
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
